[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.localnet]
project_01_favorites = "HXGTWxrBm1b2QB75xUGp6GRsvGrAtiAK72vXeYznP7uf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
